### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by di** [di/vladiate#16]
Add any (preferably all) to `.travis.yml`:

```
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
```

**Comment by csojinb** [comment]
Have you used tox? I don't remember _exactly_ how to set it up, but I could give it a go. Then you can run the tests locally in all the versions too.
