### ISSUE TITLE
add a quiet option (-q)

### ISSUE THREAD

**Issue by zoobab** [di/vladiate#57]
Hi,

After the vladiate 0.0.20, I could get the shell exitcode for success or not.

Now I would like to add a quiet option (-q) so that when I call vladiate, it silently validates, if not it will throw an error.

Best

**Comment by di** [comment]
I think this is possible once https://github.com/di/vladiate/pull/53 is merged.

@zoobab Are you suggesting that `-q` would suppress all printing and just return an exit code? Or do you think it should print an error only on failure? I think the former is probably the more common UX.

**Comment by zoobab** [comment]
Yes let's wait until #53 is merged.

I would not print anything on success (just grab the exitcode), and only output some error in case of failure.

**Comment by cal97g** [comment]
Looks like #60 solves adds quiet option

**Comment by di** [comment]
The PR is actually in #62 and needs work, the original author seems to have abandoned it.

**Comment by maleix** [comment]
Can anyone do some work about this please? It would be very useful
