### ISSUE TITLE
Extract the row number(s) where validation failed?

### ISSUE THREAD

**Issue by courserachateau** [di/vladiate#58]
How to extract the row number(s) where validation failed

**Comment by di** [comment]
@courserachateau Do you mean that you have a _single_ value could be an integer, _or_ a float?

**Comment by courserachateau** [comment]
I just realized that RangeValidator can validate both integer and floating points.. How about date time columns? How to check if the date/time format is correct?

I have daily weather data logs that need to be validated everyday.. The file has several header lines that need to be ignored. I can't just directly use LocalFile to validate the file, how do I skip rows? Sorry for asking many questions.

**Comment by di** [comment]
The `IntValidator` and `FloatValidator` validators just check whether the given value can be cast to `int` and `float` respectively. Since anything that can be cast to an `int` can also be cast to a `float`, you can just use the `FloatValidator` to check that it isn't something that isn't a valid number.

For datetime, there are so many possible formats that it's not really reasonable to provide a validator for it, but you could use a `RegexValidator` to ensure the format is correct.

> I have daily weather data logs that need to be validated everyday.. The file has several header lines that need to be ignored. I can't just directly use LocalFile to validate the file, how do I skip rows? Sorry for asking many questions.

What do these header lines look like?

**Comment by courserachateau** [comment]
https://pastebin.com/GPFb7nuF

**Comment by di** [comment]
How many columns does that CSV file have? That looks like a very long, but standard CSV header listing the column names, broken up by `\\` characters.

**Comment by courserachateau** [comment]
I inserted \\ to show the line breaks, there are 20 columns.

**Comment by di** [comment]
I see, looks like this file is technically a TOA5 file, which is similar to CSV, but has these extra rows in the headers.

One thing you could do (if you knew that there was always going to be the same number of lines to throw away) is subclass the `LocalFile` input class, something like:

```python
from vladiate.inputs import LocalFIle

class TOA5Input(LocalFile):
    def open(self):
        with open(self.filename, 'r') as f:
            lines = f.readlines()
            return lines[:1] + lines[4:]

**Comment by courserachateau** [comment]
Here's the [sample ](https://ufile.io/sxdtw)data, if you want to take a look.

**Comment by courserachateau** [comment]
I am not sure if the syntax is correct, could you please take a look, [code](https://pastebin.com/7d8bdTjZ) and the [sample ](https://ufile.io/sxdtw)data.

Error I am getting:
` RangeValidator([low:0.0])
                       ^
SyntaxError: invalid syntax
`

**Comment by di** [comment]
You need to pass those values as arguments to the `RangeValidator` class instead, for example:

```python
RangeValidator(low=0.0, high=100.0)
```

**Comment by courserachateau** [comment]
how do I redirect vladiate output to a log file?

**Comment by di** [comment]
@courserachateau You can redirect stdout and stderr for any command with the following:

```
$ command > output.log 2>&1
```

So for vladiate, that would be:

```
$ vladiate > output.log 2>&1
```

**Comment by courserachateau** [comment]
Thank you, appreciate your help.

**Comment by courserachateau** [comment]
how would I extract the row number(s) where validation failed?

**Comment by cal97g** [comment]
@di we need the program to output which lines failed validation. Envision the use case where I want to validate a user submitted input file and provide feedback on what needs to be changed to pass. I need to tell them; hey, this failed on these lines - fix that and try again

**Comment by di** [comment]
@cal97g This issue is a bit weird, the original author has changed the title and deleted all their comments for some reason. Can you open a separate issue instead?

**Comment by santilytics** [comment]
Added a PR for this https://github.com/di/vladiate/pull/74
