### ISSUE TITLE
Validators hold state if you vlad multiple times in the same context

### ISSUE THREAD

**Issue by csojinb** [di/vladiate#7]
It would be nice to be able to run validation from within python scripts or a shell repeatedly, without holding over state from the previous validation.

**Comment by dmcclory** [comment]
@di, what's happening is, we're initializing a Vlad object inside a function, like so: (in a python notebook)

```
def run_validators():
    Vlad(source=LocalFile(_output_path('plan_benefits.csv')), validators=CignaPlanBenefitInfoValidator.validators).validate()

```

if there's a problem, the output looks correct the first time we call `run_validators`:

```
ERROR:vlad_logger:  SetValidator failed 4 time(s) on field: 'Subject to Out-of-network Deductible?'
ERROR:vlad_logger:    Invalid fields: ['YES', 'N/A']
```

if we run the same function again & again though, the error counts start increasing. (And the UniquenessValidators start to break)

```
ERROR:vlad_logger:  SetValidator failed 8 time(s) on field: 'Subject to Out-of-network Deductible?'
ERROR:vlad_logger:    Invalid fields: ['YES', 'N/A']
ERROR:vlad_logger:  UniqueValidator failed 40296 time(s) on field: 'Plan ID'
ERROR:vlad_logger:    Invalid fields: ['('FMHMOX2PU047', '30', '2')', '('PMLCPX2PU020', '47', '2')', '('PMLCPX2PU030', '28', '2')', '('FMHSAX2PX041', '41', '2')'.....
```

**Comment by di** [comment]
I think doing  `validators=copy.deepcopy(CignaPlanBenefitInfoValidator.validators)` instead will solve this issue.

**Comment by dmcclory** [comment]
Yeah, I'll definitely try that out. It requires a lot of knowledge about Vladiate though.

I think this would be nicer API:
```
PlanInfoValidator(source=LocalFile(_output_path('plan_info.csv'))).validate()
```

**Comment by csojinb** [comment]
Is there any reason why you'd want to pass validators into a new Vlad _with_ state already attached? If not, we could flush them or something in the Vlad instatiation.

**Comment by di** [comment]
I decided this is a bug, because it is using the default `validators` argument (an empty `dict`) without checking to see if the class variable exists or not. Pushing a fix shortly.

**Comment by di** [comment]
> Is there any reason why you'd want to pass validators into a new Vlad with state already attached?

I guess if you wanted to override them for some reason, you would expect to be able to do this.
